#!/usr/bin/env python

import shutil
import os, stat
import glob
import sys

folder = 'IPTS_{}'.format(sys.argv[1])

raw_path = '/SNS/users/j35/git/IPTS/'

home = os.path.expanduser("~")
target_folder = home + '/notebooks/' + folder

if os.path.exists(target_folder):
   shutil.rmtree(target_folder)
    
shutil.copytree('/SNS/users/j35/git/IPTS/' + folder, target_folder)

os.chdir(target_folder)

os.system('/HFIR/CG1D/shared/start-jupyter')
