#!/usr/bin/env python

import shutil
import os, stat
import glob

raw_path = '/SNS/users/j35/notebooks/'
folder = 'IPTS_17981'

home = os.path.expanduser("~")

shutil.copytree('/SNS/users/j35/notebooks/' + folder, home+ '/notebooks/IPTS_17981/')

